import { createContext } from 'react'

const ru = {
    header_text1: "Как пользоваться?",
    header_text2: "Мои записи",
    header_text3: "Записаться к врачу",
    header_text4: "Артем Свиридов",
    list_text1: "Мой профиль",
    list_text2: "Пополнить баланс",
    list_text3: "Выйти",
    component1_text1_1: "Онлайн консультации",
    component1_text1_2: "от",
    component1_text1_3: "врачей специалистов 24/7",
    component1_text2_1: "Проконсультируйтесь",
    component1_text2_2: "сейчас",
    component1_text2_3: "или по",
    component1_text2_4: "предварительной запис",
    component1_text2_5: "со своего компьютера или c помощью нашего приложения,",
    component1_text2_6: "доступного в",
    component1_text2_7: "и",
    component1_text3: "Записаться",
    component1_text4: "Как это работает?",
    component2_text1: "Записаться к врачу",
    component2_text2: "Более 1500 врачей и более 50 разных специализаций",
    component2_text3: "Прием в удобное для вас время, без визита в клинику",
    component2_text4: "Врачи с опытом работы более 8 лет",
    component2_text5: "Понятно объясним причину недуга и дадим подробную рекомендацию",
    component2_text6: "Записаться",
    component2_text7: "мои записи",
    footer_text1: "Онлай-консульации специалистов врачей, то что предлагает данный сервис.",
    footer_text2: "В нашем веб и мобильном приложении вы найдете врачей экспертов, которые окажут вам персонализированную помощь онлайн 24/7",
    footer_text3: "Как пользоваться",
    footer_text4: "FAQ (ответы на вопросы)",
    footer_text5: "Для врачей",
    footer_text6: "О сервисе",
    footer_text7: "Контакты",
    footer_text8: "Пользовательское соглашение",
    main_text1: "Предстоящие",
    main_text2: "Прошедшие",
    main_text3: "Отмененные",
    main_text4: "Ольга Никитина",
    main_text5_1: "Педиатр",
    main_text5_2: "Оториноларинголог (ЛОР), Терапевт",
    main_text6: "Стаж 15 лет",
    main_text7: "Запланировано",
    main_text8: "Посмотреть запись",
    main_text9: "Посмотреть постановление",

}
const en = {
    header_text1: "How to use?",
    header_text2: "My notes",
    header_text3: "To make an appointment with a doctor",
    header_text4: "Artyom Sviridov",
    list_text1: "My profile",
    list_text2: "To up balance",
    list_text3: "Exit",
    component1_text1_1: "Online consultations",
    component1_text1_2: "from",
    component1_text1_3: "specialist doctors 24/7",
    component1_text2_1: "Consult",
    component1_text2_2: "now",
    component1_text2_3: "or by",
    component1_text2_4: "appointment",
    component1_text2_5: "from your computer or using our application,",
    component1_text2_6: "available at",
    component1_text2_7: "and",
    component1_text3: "Register",
    component1_text4: "How it works?",
    component2_text1: "To make an appointment with a doctor",
    component2_text2: "More than 1500 doctors and more than 50 different specializations",
    component2_text3: "Appointment at a time convenient for you, without a visit to the clinic",
    component2_text4: "Doctors with more than 8 years of experience",
    component2_text5: "We will clearly explain the cause of the disease and give detailed recommendations.",
    component2_text6: "Register ",
    component2_text7: "My notes",
    footer_text1: "Online consultations with specialist doctors who offer this service.",
    footer_text2: "In our web and mobile application you will find expert doctors who will provide you with personalized care online 24/7",
    footer_text3: "How to use",
    footer_text4: "FAQ (answers on questions)",
    footer_text5: "For doctors",
    footer_text6: "About the service",
    footer_text7: "Contacts",
    footer_text8: "Terms of use",
    main_text1: "Upcoming",
    main_text2: "Past",
    main_text3: "Canceled",
    main_text4: "Olga Nikitina",
    main_text5_1: "Pediatrcian",
    main_text5_2: "Otorhinolaryngologist (ENT), Therapist",
    main_text6: "15 year of experience",
    main_text7: "Planed",
    main_text8: "View entry",
    main_text9: "View the resolution",
}


const TranslateContext = createContext(ru, en)
export { TranslateContext, en, ru }
